import type { Category } from "../types/Variants.types";
import { useTranslation } from "react-i18next";
import React from "react";

const MAX_NAME_LENGTH = 60;

interface CategoryInfoFieldsProps {
  name: string;
  onNameChange: (name: string) => void;
  slug: string;
  onSlugChange: (slug: string) => void;
  parentId: string | null;
  onParentIdChange: (parentId: string | null) => void;
  categories: Category[];
  isParentLocked?: boolean;
  nameError?: string;
  slugError?: string;
  lockedParentName?: string;
}

export const CategoryInfoFields: React.FC<CategoryInfoFieldsProps> = ({
  name,
  onNameChange,
  slug,
  onSlugChange,
  parentId,
  onParentIdChange,
  categories,
  isParentLocked = false,
  nameError,
  slugError,
  lockedParentName,
}) => {
  const { t } = useTranslation();
  const rootCategories = categories.filter((cat) => cat.parentId === null);
  const selectedParent = categories.find((cat) => cat.id === parentId);

  return (
    <div className="space-y-6">
      {/* Category Name Field */}
      <div>
        <label
          htmlFor="name"
          className="block text-sm font-medium text-foreground"
        >
          {t("features.catalog.components.categoryInfoFields.categoryName")}{" "}
          <span className="text-destructive">*</span>
        </label>
        <div className="mt-2 flex flex-col">
          <input
            id="name"
            type="text"
            value={name}
            onChange={(e) => onNameChange(e.target.value)}
            placeholder={t(
              "features.catalog.components.categoryInfoFields.enterCategoryName",
            )}
            maxLength={MAX_NAME_LENGTH}
            className={`
              rounded-lg border px-4 py-2.5 bg-input text-foreground placeholder:text-muted-foreground
              transition-colors duration-150
              focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background
              ${nameError ? "border-destructive" : "border-border"}
            `}
          />
          <div className="mt-1 flex justify-between">
            {nameError && (
              <span className="text-sm text-destructive">{nameError}</span>
            )}
            <span
              className={`ml-auto text-xs ${
                nameError ? "text-destructive" : "text-muted-foreground"
              }`}
            >
              {name.length}/{MAX_NAME_LENGTH}
            </span>
          </div>
        </div>
      </div>

      {/* Slug Field */}
      <div>
        <label
          htmlFor="slug"
          className="block text-sm font-medium text-foreground"
        >
          {t("features.catalog.components.categoryInfoFields.slug")}
        </label>
        <div className="mt-2 flex flex-col">
          <input
            id="slug"
            type="text"
            value={slug}
            onChange={(e) => onSlugChange(e.target.value)}
            placeholder={t(
              "features.catalog.components.categoryInfoFields.autoGenerated",
            )}
            className={`
              rounded-lg border px-4 py-2.5 font-mono text-sm bg-input text-foreground placeholder:text-muted-foreground
              transition-colors duration-150
              focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background
              ${slugError ? "border-destructive" : "border-border"}
            `}
          />
          {slugError ? (
            <span className="mt-1 text-sm text-destructive">{slugError}</span>
          ) : (
            <span className="mt-1 text-xs text-muted-foreground">
              {t("features.catalog.components.categoryInfoFields.url")}{" "}
              <code className="text-foreground">/categories/{slug}</code>
            </span>
          )}
        </div>
      </div>

      {/* Parent Category Field */}
      <div>
        <label
          htmlFor="parent"
          className="block text-sm font-medium text-foreground"
        >
          {t("features.catalog.components.categoryInfoFields.parentCategory")}
        </label>
        {isParentLocked && lockedParentName ? (
          <div
            className={`
              mt-2 flex items-center gap-2
              rounded-lg border border-border bg-input
              px-4 py-2.5 text-foreground
            `}
          >
            <span>{lockedParentName}</span>
            <span className="ml-auto inline-block rounded bg-accent/20 px-2 py-1 text-xs font-medium text-accent">
              {t("features.catalog.components.categoryInfoFields.inherited")}
            </span>
          </div>
        ) : (
          <select
            id="parent"
            value={parentId || ""}
            onChange={(e) => onParentIdChange(e.target.value || null)}
            disabled={isParentLocked}
            className={`
              mt-2 w-full rounded-lg border bg-input text-foreground placeholder:text-muted-foreground
              px-4 py-2.5
              transition-colors duration-150
              focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background
              disabled:cursor-not-allowed disabled:opacity-50
              ${isParentLocked ? "border-border opacity-50" : "border-border"}
            `}
          >
            <option value="">
              {t("features.catalog.components.categoryInfoFields.noneRoot")}
            </option>
            {rootCategories.map((cat) => (
              <option key={cat.id} value={cat.id}>
                {cat.name}
              </option>
            ))}
          </select>
        )}
        {parentId && selectedParent && (
          <p className="mt-1 text-xs text-muted-foreground">
            {t(
              "features.catalog.components.categoryInfoFields.subcategoryUnder",
            )}{" "}
            <strong>{selectedParent.name}</strong>
          </p>
        )}
      </div>
    </div>
  );
};
